### ISSUE TITLE
Challenge des établissements

### ISSUE THREAD

**Issue by prololo** [prologin/site-issues#29]
> ###### Originally posted 2016-11-07 18:14 by *some anonymous* on Bitbucket

Mon score s'est enlevé à la somme des scores de mon établissement le lycée polyvalent de Cantau à Anglet.
Merci de bien vouloir régler ce problème.

**Comment by seirl** [comment]
> ###### Originally posted 2016-11-07 18:57 by [serialk](https://bitbucket.org/serialk/) on Bitbucket

Bonjour,

Le préposé aux scores manquants est en congé maladie.

Cordialement.

**Comment by Zopieux** [comment]
> ###### Originally posted 2016-11-07 19:03 by [Zopieux](https://bitbucket.org/Zopieux/) on Bitbucket

Plus sérieusement, nous prenons en compte l'âge des candidats pour le décompte des points. Je rappelle en effet que seuls les candidats nés en 1996 ou après peuvent concourir aux étapes suivantes de Prologin. Cela s'applique également au challenge des établissements.

Je constate que tu n'as pas renseigné ta date de naissance dans le formulaire, le système ne peut donc pas savoir si tu es éligible.

Nous avons introduit ce changement il y a quelques jours seulement, c'est pour cela que tes points apparaissaient avant.
