### ISSUE TITLE
Bouton "Editer le profil"

### ISSUE THREAD

**Issue by prololo** [prologin/site-issues#31]
> ###### Originally posted 2016-12-29 23:17 by [Brfrance](https://bitbucket.org/Brfrance/) on Bitbucket

Bonsoir,

Le bouton "éditer le profil" est présent sur toutes les pages d'utilisateurs, renvoyant évidemment à une 403 lorsque l'on clique sur un autre lien que le sien ... 

Bonne soirée ;-) !

**Comment by Zopieux** [comment]
> ###### Originally posted 2016-12-30 09:15 by [Zopieux](https://bitbucket.org/Zopieux/) on Bitbucket

Merci on va corriger.

**Comment by Zopieux** [comment]
Corrigé dans prologin/site@a3ca1f9.
