### ISSUE TITLE
Probleme exercices: Comparer les chaines

### ISSUE THREAD

**Issue by cpicard443** [prologin/site-issues#32]
Voici le lien de l'exo:
https://prologin.org/train/2003/qualification/comparer_des_chaines

Verifiez par vous meme mais le dernier test est mauvais

**Comment by Zopieux** [comment]
Testé et confirmé, merci.

prologin/site#88

**Comment by Zopieux** [comment]
@cpicard443 c'est maintenant corrigé, ainsi que pour de nombreux autres exercices qui avaient le même problème en coulisse.

Comme tu peux le constater dans la page de [ta soumission](https://prologin.org/train/2003/qualification/comparer_des_chaines/125815), il y a maintenant tous les tests.
