### ISSUE TITLE
Support de Rust pour les exercices ?

### ISSUE THREAD

**Issue by MaloJaffre** [prologin/site-issues#35]
Apparemment, [`camisole`](https://camisole.prologin.org) supporte le language Rust, mais il n'apparait pas dans les languages supportés par le site.

Pourriez-vous le rajouter, si cela ne vous ennuie pas (malgré le non-support par `metalang`) ?

Si il y a besoin de changements pour `camisole`, indiquez-les moi, et j'essaierais d'envoyer un PR.

**Comment by Zopieux** [comment]
@seirl tu regardes pour les facteurs time/mem ?

**Comment by seirl** [comment]
Je ne pense pas qu'il y ait besoin de facteurs pour Rust.

**Comment by MaloJaffre** [comment]
Selon http://benchmarksgame.alioth.debian.org/u64q/rust.html, Rust est dans le même ordre de grandeur en temps et mémoire que C/C++ (pas de runtime, ni de GC, comme C++)

**Comment by MaloJaffre** [comment]
Selon http://benchmarksgame.alioth.debian.org/u64q/rust.html, Rust est dans le même ordre de grandeur en temps et mémoire que C/C++ (pas de runtime, ni de GC, comme C++).

**Comment by seirl** [comment]
Fixed in 52028407c6bd6ddcb74015d699f56ab1152977f8
