### ISSUE TITLE
Le premier exercice d'inscription 2018 ne fonctionne pas

### ISSUE THREAD

**Issue by JNa0** [prologin/site-issues#36]
J'ai essayé en Javascript et en Python et rien à y faire, aucun de mes programmes ne retourne de valeur. Je crois pourtant avoir bien fait : 

`def bataille_de_crepe0(n, marchand1, marchand2):`

    # mon code avec des instructions de type "return value"
`n = int(input())`
`marchand1 = int(input())`
`marchand2 = int(input())`
`bataille_de_crepe0(n, marchand1, marchand2)`

**Comment by multun** [comment]
Bonjour !

As-tu pensé à afficher tes valeurs sur la sortie standard, par exemple à l'aide de `print()` en python ?

En effet, c'est ce que le sujet stipule:
```
Vous afficherez un entier
```
Retourner la valeur ne suffit pas, même si l'interprêteur python ou javascript te l'affiche
