### ISSUE TITLE
Erreur problème 5 qualification 2019

### ISSUE THREAD

**Issue by Lasssima** [prologin/site-issues#38]
Je pense qu'il y a une erreur dans l'exemple 2 du problème 5, on retrouve le schéma aussi au rang 13.
![sans titre](https://user-images.githubusercontent.com/46249256/50541735-fb9a0900-0bab-11e9-829a-e2d4eb0f7509.png)

**Comment by fnareoh** [comment]
Non, l'exemple est correct, la partie que tu montres n'est pas un match : dans le groupe d'amis, l'ami de plus petite taille est en deuxième position en partant de la droite, alors que dans les statuettes que tu indiques, la plus petite est en deuxième position en partant de la gauche ! 

N'hésite pas à poser d'autres questions si tu ne comprends pas ma réponse, en revanche ici n'est pas vraiment l'endroit, ouvre plutôt un nouveau sujet ici https://prologin.org/forum/general-2
