### ISSUE TITLE
Soumissions bloquées

### ISSUE THREAD

**Issue by MaloJaffre** [prologin/site-issues#40]
Bonjour,
Il semble que les soumissions de solutions ne fonctionnent plus, et restent bloquées en cours de correction, en particulier sur Manchots Glisseurs.

**Comment by multun** [comment]
Houla oui en effet ! normalement c'est bon. désolé !

**Comment by MaloJaffre** [comment]
Oui, effectivement cela refonctionne maintenenant.
Merci beaucoup!
