### ISSUE TITLE
Bug du questionnaire pour le CTF 1 (2020)

### ISSUE THREAD

**Issue by vdng9338** [prologin/site-issues#41]
Lorsque je soumets ma réponse pour le CTF 1, une erreur "Internal Server Error" s'affiche, puis quand je retourne au questionnaire, toutes mes autres réponses ont disparu...

**Comment by haltode** [comment]
Bonsoir, le problème a été résolu hier, tu peux à nouveau sauvegarer tes réponses. Merci de nous avoir prévenu et désolé du dérangement.
