### ISSUE TITLE
Mauvaise correction

### ISSUE THREAD

**Issue by cyacinewsh** [prologin/site-issues#44]
Bonsoir , j'ai envoyé le programme du challenge 1 ,en étant sûr qu'il fonctionne et qu'il produit le résultat attendue par l'énoncé. Cependant, on m'indique qu'il ne fonctionne pas pour une raison que je ne comprend pas...Pourrai-je vous l'envoyer afin qu'une personne physique le corrige s'il vous plait? Merci

**Comment by remi-dupre** [comment]
Bonjour,

Il faut être très rigoureux sur les formats d'entrée / sortie de ton programme. Lorsque tu exécute un test se qui est affiché doit être exactement le texte donné en entrée, suivi par le texte de ta sortie.

Par exemple pour le premier exercice à l'issue d'un test tu dois retrouver exactement ça dans la console:

```
3
67 121 88
200
```

Dans cet exemple c'est toi qui a écrit ou collé les deux première lignes (à noter que dans des cas d'usage plus avancés elles peuvent même être absente). La dernière ligne est ce que ton programme a affiché.

Le plus simple est probablement de réutiliser le code donné en cliquant sur le bouton **Code à compléter** en dessous du champs de soumission, en bas de l'énoncé. Si tu remplis juste le code de la fonction donnée, tu es certain de respecter le format d'entrée ! :smiley:

**Comment by Zopieux** [comment]
![2020-01-12 18-39-28](https://user-images.githubusercontent.com/81353/72223035-45615180-356b-11ea-8f9e-c963ec9e47b9.gif)
