### ISSUE TITLE
Module archive avec les anciens sujets

### ISSUE THREAD

**Issue by seirl** [prologin/site-issues#9]
> ###### Originally posted 2015-10-28 15:47 by [serialk](https://bitbucket.org/serialk/) on Bitbucket

**Comment by Zopieux** [comment]
> ###### Originally posted 2015-10-28 17:48 by [Zopieux](https://bitbucket.org/Zopieux/) on Bitbucket

T'aurais pu mettre le component quand même.

**Comment by seirl** [comment]
> ###### Originally posted 2015-11-21 22:30 by [serialk](https://bitbucket.org/serialk/) on Bitbucket

Fait
